# with open("./Misc/sample.txt","w") as file:
#     file.write(
#     "Golang is easy to learn.\n"
#     "\n"
#     "Golang is a powerful language.\n"
#     "Golang is easy to learn.\n"
#     "Java is popular.\n"
#     "Golang is powerful.\n"
#     "\n"
#     "File handling    is important.\n"
#     "File handling is important.\n"
#     "\n"
#     "I love Golang programming.\n"
#     "Golang is easy to learn.\n"
#     "\n"
#     "Practice Golang    every day."
# )

# # 135. Read a file and replace a particular word.
# oldword = "Golang"
# newword = "python"
# with open("./Misc/sample.txt","r") as file:
#     content = file.read()
# content = content.replace(oldword,newword)
# with open("./Misc/sample.txt","w") as file:
#     file.write(content)
# print(content)


# # 136. Read a file and replace multiple words.
# replacements = {"Python": "Java", "easy": "simple", "powerful": "strong"}
# with open("./Misc/sample.txt","r") as file:
#     content = file.read()
# for oldword,newword in replacements.items():
#     content = content.replace(oldword,newword)
# with open("./Misc/sample.txt","w") as file:
#     file.write(content)
# print(content)

# # 137. Remove blank lines from a file.
# with open("./Misc/sample.txt","r") as file:
#     lines = file.read().splitlines()
# with open("./Misc/sample.txt", "w") as file:
#     for line in lines:
#         if line.strip():
#             file.write(line + "\n")

# 138. Remove duplicate lines.
with open("./Misc/sample.txt","r") as file:
    lines = file.read()
with open("./Misc/sample.txt", "w") as file:
    for line in lines:
        if line.strip():
            file.write(line + "\n")


# 139. Add line numbers to every line.
# Input: filename = "./Misc/sample.txt"

# 140. Read a file, modify its contents, and write the result into another file.
# Input: input_filename = "./Misc/sample.txt", output_filename = "./Misc/output.txt"

# 141. Read a file and remove unnecessary spaces.
# Input: filename = "./Misc/sample.txt"

# 152. Read logs from a file and print each line.
# Input: filename = "./Misc/sample_app.log"

# 153. Sort logs based on timestamp.
# Input: filename = "./Misc/sample_app.log"

# 154. Find all ERROR logs.
# Input: filename = "./Misc/sample_app.log"

# 155. Count INFO, WARNING, and ERROR logs.
# Input: filename = "./Misc/sample_app.log"

# 156. Find the first error in the log.
# Input: filename = "./Misc/sample_app.log"

# 157. Find the latest error.
# Input: filename = "./Misc/sample_app.log"

# 158. Find the number of errors per day.
# Input: filename = "./Misc/sample_app.log"

# 159. Find the most common error message.
# Input: filename = "./Misc/sample_app.log"

# 160. Find all logs generated by a particular user.
# Input: filename = "./Misc/sample_app.log", username = "alice"

# 161. Find logs between two timestamps.
# Input: filename = "./Misc/sample_app.log", start_timestamp = "2026-08-14 10:00:00", end_timestamp = "2026-08-14 12:00:00"

# 162. Find the earliest and latest timestamp.
# Input: filename = "./Misc/sample_app.log"

# 163. Detect duplicate log entries.
# Input: filename = "./Misc/sample_app.log"

# 164. Find the number of requests per minute.
# Input: filename = "./Misc/sample_app.log"

# 165. Find the busiest hour.
# Input: filename = "./Misc/sample_app.log"

# 166. Find users who generated more than N errors.
# Input: filename = "./Misc/sample_app.log", n = 3
with open('./Misc/sample_app.log')

  #Given millions of log lines, find the top 10 error types without loading the entire file into memory.

uniqe_errors = {}
# count_connection_refused = 0
with open('./Misc/sample_app.log') as f:
    for line in f:

        if "ERROR" in line:
            split_list= line.split(" ")

            error_type = split_list[-1].strip("message=\n")

            if error_type not in uniqe_errors:
                uniqe_errors[error_type] = 0
            
            uniqe_errors[error_type] = uniqe_errors[error_type] + 1


print(uniqe_errors)
# {
#     PermissionDenied : '',
#     FileNotFound : ''
# }  